### PR TITLE
hotfix/UTC-233: Add focus-visible state

### PR DESCRIPTION
**Pull request by bmartinez287**
Screen Shot 2021-08-13 at 4 17 00 PM
Screen Shot 2021-08-13 at 4 16 47 PM

### CODE REVIEW

**Review by UTCbridget — APPROVED** [review]
To quote a good friend of mine... "Nice."

**Comment by bmartinez287** [comment]
It makes a big difference if you are just tabbing trough the page. I'm not sure on that color but that seems to have a decent contrast.
I may swap it for one for talwindcss border-yellow-600
https://tailwindcss.com/docs/border-color

**Comment by UTCbridget** [comment]
I like the UTC gold and I like the dashed line.

**Review by brittrich — COMMENTED** [review]
Awesome, Bernardo! Looks good.

**Review by brittrich — APPROVED** [review]

**Comment by bmartinez287** [comment]
The challenge with utcgold is that it could be used somewhere on the page. Because it could be used for something else the contrast might not be good if it ends up on top of light color component. Since this is such a global component thats easier to change lets tested it with this color for now.

**Pull request merged**
