### PR TITLE
UTC-326: Add hero zoom effect and button text.

### PR DESCRIPTION
**Pull request by UTCbridget**
This PR combines Particle issues #326 and #342. 

#326 discusses the possibility of add a zoom effect on the hero image. This is done through CSS and can be added to any image with a class. This can also be added to other components with images (except the UTC Hover Image component as it already has a hover effect) by adding a boolean, for example, "Zoom the image on hover?" and then add that variable in twig as a class to that component.

#342 discusses the need (and requested by a high UTC designer for marketing purposes) for the ability to add any text dynamically to the button link on the hero. Currently, the button text is hard-coded to "Learn More". The reason is that a problem arose with the Link field not offering a maxlength attribute, thus we implemented "Learn More" to prevent "bumper sticker buttons from being used by section editors in the hero, when the hero is made available to section editors. This is solved with the module [maxlength](https://www.drupal.org/project/maxlength). Locally, I have implemented version  8.x-1.0-rc1 released 26 June 2020. There is a dev version that was last update 26 Aug 2021. The rc1 version works very well. Two issues are posted that do not apply to our application. This can be used in a variety of applications/components. The module, of course, cannot be PRed to utccloud until this PR is merged.

**Hero zoom effect and example of a dynamic button text field:**

hero-zoom-and-button2

**Admin interface with new maxlength module:**

hero-link-restriction

### CODE REVIEW

**Comment by bmartinez287** [comment]
Relates #340.
So in regards to the text option, I think we should make it a taxonomy and let people chose from pre approved list of options.
If the option its not there they can request something and we could add it to that drop down.

**Comment by UTCbridget** [comment]
Good idea, but I'm not sure that would work for one of our designers. I did limit the maxlength, though. So that should solve the problem. Like the example here, "Find a Friday" is so specific. It likely would not make the taxonomy list.

**Comment by bmartinez287** [comment]
In regards to the motion feature, I'm a little concern that it might create motion sickness. However, I'm ok with it if we turn it into an optional feature that can be turn on and off with a checkbox. I know it takes more work, but if we make it the default and we get a complain it would take hours to reach production.
How do we reduce motion sickness? idk, maybe zooming in a little slower.

**Comment by UTCbridget** [comment]
I can slow it down and make it a checkbox. I was think the same thing, but for other components. It's a good idea to do with the hero, too.

**Comment by bmartinez287** [comment]
Yeah, I can see that. We probably should discuss that on a Tuesday/Thursday meeting.
Limiting the amount of characters they can use will eventually bite us back as well.  Someone will request one that's too long. Not sure which one would be better however for backwards compatibility purposes we also have to make the default text learn more. @brittrich what do you think?

**Comment by UTCbridget** [comment]
I think we just tell people who want a longer one, "I'm sorry, but the design of this component won't support that."

**Comment by bmartinez287** [comment]
This looks good, can we add another if statement to that line to add the animation conditionally?

**Comment by UTCbridget** [comment]
Actually, I've already done all that. The last (100 or so?) commits were undoing and redoing dist files.... again. >:{ 
I'm about to (hopefully) push really nice code.

**Comment by UTCbridget** [comment]
Latest and greatest: Add boolean field (which can be reused for any image except hover images) for option to zoom image or not. Also, made link text required only when a URL is entered. If I didn't do this, the link field automatically populated the field with the URL, making the button way too long. The maxlength was reduced to 20 from 25 as well.

New admin with zoom option:
hero-zoom-and-button-admin

New admin with link required when URL is entered. Maxlength reduced to 20:
hero-zoom-and-button-link-req


New zoom effect:
hero-zoom-and-button

**Review by bmartinez287 — APPROVED** [review]

**Comment by brittrich** [comment]
I think this looks great! The zoom effect is constant, right? Or, is it on hover? Just curious if only activating it only hover would make it less likely to throw anyone off accessibility-wise. Although it'd be less interesting, for sure. 

Max length is a good way to keep it within the design boundaries, I think, while allowing flexibility.

**Comment by UTCbridget** [comment]
Thanks, Brittany. The zoom effect is only hover so as not to make people dizzy ;) The gif is a loop so it doesn't really show that very well.

**Pull request merged**
