### PR TITLE
warm ups

### PR DESCRIPTION
**Pull request by ghost**
# Pull Request

Closes Issue #X

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Hi @UTCWeb/utcclouddevs looking into getting back onto the Development track. I am not sure why this commit was included. I pulled the recent changes to update my develop branch and it created a commit for changes that were already on canonical develop. I'm probably confusing myself. Any insight here would be helpful. Thanks.

**Comment by ghost** [comment]
> Hi @UTCWeb/utcclouddevs looking into getting back onto the Development track. I am not sure why this commit was included. I pulled the recent changes to update my develop branch and it created a commit for changes that were already on canonical develop. I'm probably confusing myself. Any insight here would be helpful. Thanks.

Looks like I had to do a bit of git branch management as I had forked particle from phase2 already. I also forgot to create a new branch. A bit rusty over here. 😅

**Comment by bmartinez287** [comment]
To answer that question accurately, I need to know which steps you followed. Most likely, you committed the build folder. Don't commit that folder. The build folder gets generated dynamically.
O cool, yeah forking from phase2 directly could do that.

**Comment by ghost** [comment]
> To answer that question accurately, I need to know which steps you followed. Most likely, you committed the build folder. Don't commit that folder. The build folder gets generated dynamically.
> O cool, yeah forking from phase2 directly could do that.

Okay. I remember seeing a few things about not committing and ignoring a portion. We should add that information into the README.

**Comment by bmartinez287** [comment]
Yeah, that said. I did read about a way in which we can git ignore that folder and still have it built by Travis. I have to test quite a few items though. One of them that Travis does not ignore it and then that Acquia deploys with it.
So it might change slightly in the next few days.

**Review by stevendshelton — APPROVED** [review]

**Comment by ghost** [comment]
Relates to #70

**Comment by ghost** [comment]
> Yeah, that said. I did read about a way in which we can git ignore that folder and still have it built by Travis. I have to test quite a few items though. One of them that Travis does not ignore it and then that Acquia deploys with it.
> So it might change slightly in the next few days.

Sounds good sir.

**Pull request closed without merging**
