### PR TITLE
UTC-574: Fix jumpy hero on mobile.

### PR DESCRIPTION
**Pull request by UTCbridget**
This resolves issue #574 using css. The issue stemmed from overrides of the the bootstrap defaults in theMag: .container-full having padding and its child .row having -margins. 

not-glitchy-hero

### CODE REVIEW

**Comment by UTCGilligan** [comment]
@UTCbridget In the animation, and also in browsers, there is a box above the hero image that looks like it's a "loader" GIF or icon that is missing. Any idea what is causing that?

**Comment by UTCbridget** [comment]
Yes, that's the blazy loader for the background image. Do you want me to turn it off?

**Comment by UTCGilligan** [comment]
Seems like it should have an icon in it or not be transparent/invisible, because it looks like a missing image.

**Comment by UTCbridget** [comment]
I'll make it transparent.

**Comment by UTCbridget** [comment]
No more loader. I think the image loads pretty quickly without it and it's a background image.  The main image is ok.

no-blazy-loader

**Review by UTCGilligan — APPROVED** [review]
Thanks!

**Pull request merged**
