### PR TITLE
UTC-310: Avoids user from hiding all cards from a block at once

### PR DESCRIPTION
**Pull request by bmartinez287**
checks whether all cards have been hidden and it warns the user about it.
Screen Shot 2021-08-28 at 10 09 47 PM
Screen Shot 2021-08-28 at 10 10 07 PM

### CODE REVIEW

**Comment by bmartinez287** [comment]
if you guys have feedback on a different approach that be great to know.

**Comment by UTCbridget** [comment]
My only thought is there might be a scenario that they may want to hide all the cards: say they want go ahead and enter them in, but don't want to show them perhaps until a later date? Also, the headline would show to the public should they save it with the headline showing. If we were to implement this, we probably should put a role condition on it.

**Comment by UTCbridget** [comment]
We could do a jquery alert: https://discourse.slimframework.com/t/how-to-load-an-alert-inside-an-if-statement-twig/2362

**Comment by bmartinez287** [comment]
True, but the issue is that is easy to forget them and they will become dead space on the page.
Plus is hard to find the edit button once it collapses making it so they will create a new one thinking the older one got deleted.

**Comment by UTCbridget** [comment]
That's a good point. If we could prevent the selections in the first place, that would be nice.

**Comment by bmartinez287** [comment]
Preventing the selection would help but that be an added layer in case they were to hide them all.

**Comment by UTCbridget** [comment]
So what about some jquery added when a user is logged in only. In this instance, if the user has chosen 3 cards and selects all 3 cards as placeholders, whichever card is the 3rd selected cannot be selected and the user gets an alert:

prevent-hiding-all-cards

**Pull request merged**
