### PR TITLE
UTC-116: Refactored employee blocks php

### PR DESCRIPTION
**Pull request by bmartinez287**
Screen Shot 2020-10-26 at 4 10 33 PM
Screen Shot 2020-10-26 at 3 08 21 PM
Screen Shot 2020-10-26 at 4 15 52 PM

I got view modes in there. The way there I added them works although I probably can update it later as my knowledge in PHP and the entity browser grows. if you guys have suggestions let me know.

Right now what triggers the change is an if statement.

### CODE REVIEW

**Review by stevendshelton — APPROVED** [review]

**Review by UTCGilligan — COMMENTED** [review]
Still missing from template: employee prefix (maybe not needed due to AP style direction from Gina?), employee suffix (needed, possibly need to accommodate multiple taxonomy terms, comma separator ", " before each).

Chris Smith, PhD, APRN, FNP-BC
Dr. June Hanks, PT, DPT, PhD, CWS, CLT

**Review by brittrich — APPROVED** [review]
Looks good! After this goes in, I can tie the smaller wide cards to the small teaser card view mode (unless you've got other plans for it).

**Comment by bmartinez287** [comment]
In regards to the prefix suffix, that will probably come in a different refactor PR altogether. That's a broader challenge that poses more design/implementation implications. Plus we still lack some research on such subjects.

The goal is to have this in development soon. I'm trying to troubleshoot another issue that I found out about yesterday(non-related). Once I'm done with all I will focus on testing this.

**Comment by bmartinez287** [comment]
https://www.drupal.org/project/entity_browser_block/issues/3172230
While troubleshooting another issue I found this awesome patch.
This will make it so only the views that are assigned to the bundle will show. Allow us to avoid issues with Departamental footers, aggregator, or any other time of custom view that has not been chosen.
I probably add it to this PR on a separate commit.
```
"drupal/entity_browser_block": {
                "Only show enabled view modes" : "https://www.drupal.org/files/issues/2020-09-21/3172230-2-filter-view-mode.patch"
},
```

**Pull request merged**
