### PR TITLE
Feature/UTC-179 by the numbers block

### PR DESCRIPTION
**Pull request by brittrich**
Relates to feature request #179.

This may need some more work, but what I've got so far:

- Block can handle up to eight inputs but adapts to less (even numbers look better, of course).
- Can select background image, if desired (uses same taxonomy as hero)
- Can select light or dark
- Two view modes:
  - Full: data spans across, can select one row or two rows.
  - Default: has a feature box in a different color where inputs 6-8 are displayed.

Are there additional features (or less features) that would be useful for this?

Examples:

data-sample-1

data-sample-2

data-sample-4

### CODE REVIEW

**Comment by UTCbridget** [comment]
Good work, Brittany! Would it be possible to add a font awesome feature to add more visual interest?

**Comment by bmartinez287** [comment]
I wonder if the numbers should be bigger. Fontawesome it's a hard one to pull off correctly on this one. Primarily because I haven't seen that many higher examples with it. Or at least I haven't found them. @UTCbridget do you have some higher ed examples in mind for this type of block.

With all the changes inside CommMar, there is going to be more involvement from Stephen R. In our last meeting, we talked about Figma or Adobe XD designs that he could open, see, comment, and approve.
https://www.learnwithjason.dev/introduction-to-figma-for-developers?fbclid=IwAR3WAb4yorNyF5U3j-Q-tO64zayBXlo_nlNk_FPB1lUTvlve-jdK2swA5B4
https://www.youtube.com/watch?v=qKRq-tFixWE&ab_channel=AdamWathan

We need some type of workflow to get the visuals out of the way and preapproved and for the steering committee to have an easy choice on them(if they need to be involved).
As time allows take a look at the first video is an interesting walkthrough. @brittrich

**Comment by UTCbridget** [comment]
@bmartinez287, you are right that there are not many out there. Most fact pages are extremely boring. Here are some that do use some type of visuals, though. Some are good, some are not, but worth a look-see. I don't think facts have to be boring. 

Images not icons, but add visual interest
https://www.ucdavis.edu/about/rankings

Nice clean use of icons
https://www.purdue.edu/purdue/about/index.php

Nice clean use of icons
https://onlinedegrees.purdue.edu/purdue-global/?&source=SF55042&ve=62295&utm_source=Google&utm_medium=CPC&utm_campaign=pgo_sem_gsa_pros_inq_br_purdue_np_semibr_nd_ext-VQ2-g-VQ6-535153530934-VQ16-c-Target-aud-934233455737:kwd-118244762&adid=&gclid=EAIaIQobChMI_9ujtciD8gIVeQaICR30rQodEAAYASAAEgLZEfD_BwE&gclsrc=aw.ds

Nice clean use of icons
https://sc.edu/about/south_carolina_at_a_glance/index.php

Good use of icons
https://design.ncsu.edu/about/rankings/

Mix of icons and numbers
https://www.unc.edu/about/by-the-numbers/

Some icons used
https://www.law.miami.edu/about/fast-facts

One image with lots of facts with icons
https://smp.business.wfu.edu/fact-sheet/

Uses a PDF, but has lots of icons
https://admissions.fsu.edu/publications/recruitment/recruitment_2017.pdf

Ugly, but not plain
https://recreation.gmu.edu/about-us/facts-and-figures/

Some visuals
https://www.etsu.edu/fachistory/

Some visuals
https://www.mtsu.edu/

**Comment by UTCGilligan** [comment]
I like the FA idea also, but UTC Cards do pretty much the same thing already, just a different look. Maybe just add optional icon or image similar to cards... image would be useful for user-created graphics.

**Comment by brittrich** [comment]
I agree with you, @UTCbridget, data doesn't have to be boring! :) Maybe there is a way to add the icon (and/or image) option to this. @UTCGilligan is right, we have a way to accomplish something like some of the examples above using the cards...if we are looking for a three column type option with icons (similar to purdue). I haven't looked back at the icon option on cards in a while...I wouldn't be surprised if some small improvements were needed to make it more useful for pages like this. I remember that being a particularly tricky build at the time to include the FA icons, but it may just have been because it one of my first.

For a block with more data like this, there may still be a way to make it more visual, though! Happy to explore some options. Thanks for the examples as well!

**Comment by brittrich** [comment]
> I wonder if the numbers should be bigger. Fontawesome it's a hard one to pull off correctly on this one. Primarily because I haven't seen that many higher examples with it. Or at least I haven't found them. @UTCbridget do you have some higher ed examples in mind for this type of block.
> 
> With all the changes inside CommMar, there is going to be more involvement from Stephen R. In our last meeting, we talked about Figma or Adobe XD designs that he could open, see, comment, and approve.
> https://www.learnwithjason.dev/introduction-to-figma-for-developers?fbclid=IwAR3WAb4yorNyF5U3j-Q-tO64zayBXlo_nlNk_FPB1lUTvlve-jdK2swA5B4
> https://www.youtube.com/watch?v=qKRq-tFixWE&ab_channel=AdamWathan
> 
> We need some type of workflow to get the visuals out of the way and preapproved and for the steering committee to have an easy choice on them(if they need to be involved).
> As time allows take a look at the first video is an interesting walkthrough. @brittrich

@bmartinez287 I LOVE the idea of having approved visuals to develop (and re-develop) from from instead of just making my best guess as I go ;). I was excited to hear about the steering committee and Stephen's involvement from Susan as well. I'll watch these and let me know if anything else comes up that I need to start learning or looking at around this.

**Comment by bmartinez287** [comment]
I started looking at this today. It looks great. Check that figma link I sent you on teams, I'm using their free account to check it out and see how we could use it to quickly iterate trough design items and have some feedback from the design team.

**Comment by bmartinez287** [comment]
The key is to make it easier for them to approve  and poke around and for us to be able move faster.
https://www.learnwithjason.dev/introduction-to-figma-for-developers?fbclid=IwAR3WAb4yorNyF5U3j-Q-tO64zayBXlo_nlNk_FPB1lUTvlve-jdK2swA5B4
That paired with the video above would make it really easy to get feedback. @brittrich

**Comment by brittrich** [comment]
@UTCbridget and @bmartinez287 

Okay, so I've got a Figma that's in decent condition on this now. I've worked a bit on how we might be able to use the existing FA field option on this in a few simple ways: https://www.figma.com/file/yrmyGXChCboUodp6wDdh1n/By-the-Numbers-Block?node-id=0%3A1 

I'd like to know any edits you'd like to see on the blocks if you want to add comments to the Figma. I don't know that I'd call this Figma "committee ready"....it could be cleaner and clearer. If this is something that needs to go that far, please feel free to edit or lmk and I can clean it up further and do a mobile version of each as well....just didn't want to sink too much time on prototyping without checking.

Sidebar...thoughts on first Figma experience:

- It's a neat tool! Nice to be able to link items together, use code a bit, etc.

- Although it might add more time to the process, I get how it'd be useful for prototyping.

- I'll admit, this was probably easier because most of it was already built so I'd already thought through how to build the block/fields in Drupal, when to use grid vs. flex for alignment, wrapping, etc. I don't know how easy it would be to consider those things while bulding a design from scratch in Figma without doing some work in Drupal at the same time. Some things you think are possible (e.g. adding a circle to the icons...) just end up not being possible when you get in and try it out IRL.

- I'm happy to build from someone else's prototypes...if my time is better spent on that side of things...it was interesting to understand how this works, though, either way.

**Comment by bmartinez287** [comment]
xvk867@mocs.utc.edu. Could you add that account to the figma file? I used my google account for it and right now it tells me I don't have permission. @brittrich

**Comment by UTCbridget** [comment]
I'll need bridget-hornsby@utc.edu added as well as I'm having the same issue as @bmartinez287.

**Comment by brittrich** [comment]
Icons are added using the Font Awesome field. This field allows the user to choose the icon size. I added a note about this to the user interface to try to help them choose something of an appropriate size (e.g. 3x). Too confusing or too much risk? It's also possible we use a text input field and link to the FA website for them to pick the icon they want to use and grab the code, that would allow us to control sizing consistently in the code.

by-the-numbers-edit

by-the-numbers-mobile

by-the-numbers

**Comment by brittrich** [comment]
@bmartinez287 and/or @UTCbridget do you think I can go ahead and merge this? It may need some additional tweaks, but it might be nice to have it in develop for everyone to explore in the meantime and give suggestions. I can make sure my utccloud PR does not turn it on for any content types besides the homepage one.

**Comment by bmartinez287** [comment]
content.field_highlight_info_1. I think there's a way of reusing these fields that will not only simplify the twig files but also make it easier to reuse.
Can you share a screenshot of what fields are needed per item? Like the icon, the data, and the description.

**Comment by bmartinez287** [comment]
Never mind the question above, I can see it on that video. That's pretty creative.

**Comment by UTCbridget** [comment]
I think this should be made available on all homepage content types, UTC, Admin, and Academic. This as well as the UTC Hero. This is really great, btw.

**Comment by bmartinez287** [comment]
maybe we should reuse field_highlight_info field as to avoid having field_highlight_info_1 field_highlight_info_2 field_highlight_info_3 and more. that could help reduce the number of fields and we might be able to do a forloop to iterate trough the data. Thoughts? @brittrich.
I will merge this one in so you can proceed with testing.

**Comment by brittrich** [comment]
> maybe we should reuse field_highlight_info field as to avoid having field_highlight_info_1 field_highlight_info_2 field_highlight_info_3 and more. that could help reduce the number of fields and we might be able to do a forloop to iterate trough the data. Thoughts? @brittrich.
> I will merge this one in so you can proceed with testing.

Are you thinking similar to how we iterate in the button group? One field that can be replicated as needed?

**Comment by bmartinez287** [comment]
yeah, that be great. After looking at cards and learning how we could improve blocks that have many fieldsets that's something that has come up. It's a meet-on-the-middle type approach. The button group is a great example. @brittrich

**Comment by bmartinez287** [comment]
@brittrich so each item has 3 items right? a title, description, and fa-awesome field.
I created a custom field widget that should do the same thing by extending the fa-awesome field to include two more items.
Think of it like the link field which includes a title and the link.
https://www.lullabot.com/articles/extending-a-field-type-in-drupal-8
I probably add it tomorrow so we can test it and get some feedback.

**Comment by bmartinez287** [comment]
By extending the field this block would have a very similar experience to buttons blocks.

**Comment by brittrich** [comment]
> @brittrich so each item has 3 items right? a title, description, and fa-awesome field. I created a custom field widget that should do the same thing by extending the fa-awesome field to include two more items. Think of it like the link field which includes a title and the link. https://www.lullabot.com/articles/extending-a-field-type-in-drupal-8 I probably add it tomorrow so we can test it and get some feedback.

Yes to three items! Did this go in? I'll look around for it. That's a great solution!

**Pull request merged**
