### PR TITLE
hotfix/UTC-233: ADA for the menu block

### PR DESCRIPTION
**Pull request by bmartinez287**
Allows a user to skip sidenav

### CODE REVIEW

**Review by UTCbridget — APPROVED** [review]
So putting the link on the bottom means that the reader will automatically go the top of the next div. Brilliant!

**Comment by UTCbridget** [comment]
Should we put a return to side navigation link at the bottom of the second region in case they want to navigate to a sub page?

**Review by UTCGilligan — APPROVED** [review]

**Comment by bmartinez287** [comment]
So returning back to it like that would be tricky. I imagine though that it would be something similar to what they will do if they wanted to back to the brandbar, they refresh the page.

**Comment by UTCbridget** [comment]
That's an option, but not very friendly. I was wondering if a hidden link below the content would work. Example: We add an id to the side-nav, put a return link with that id as the anchor at the bottom of the content (which will show on all pages, but we could have hidden instructions to that affect), then if there is anchor, it'll return. If there isn't an anchor, obviously, it won't return, but the hidden instructions would explain it somehow. ie., `<a href="#sidebar-navigation" title="Go back to the sidebar if it exists" class="sr-only">Return to the sidebar navigation if applicable for this page</a>` Just an idea.

**Comment by bmartinez287** [comment]
yeah, we need to add more research into adding a return somewhere so it be strategic. I will merge this for now and we can refactor it later to include such change.

**Pull request merged**
