### PR TITLE
UTC-204: Top Nav Active Links

### PR DESCRIPTION
**Pull request by bmartinez287**
Relates #204 
Relates #https://github.com/UTCWeb/utccloud/issues/1527

### CODE REVIEW

**Comment by bmartinez287** [comment]
**Active state**
Screen Shot 2021-03-31 at 3 35 51 PM
**Hover state**
Screen Shot 2021-03-31 at 3 33 55 PM
**Extra credit**: A way to handle long menu items. This a primarily seen if someone translates the page into a language that might split one word into three or more.
Screen Shot 2021-03-31 at 3 26 57 PM
I added the flow wrap in case they translate our menu with google translate or something like it.

**Comment by bmartinez287** [comment]
Resources:
https://www.drupal.org/docs/theming-drupal/twig-in-drupal/functions-in-twig-templates
https://www.drupal.org/project/twig_link_attributes
https://tailwindcss.com/docs

**Review by UTCGilligan — APPROVED** [review]

**Comment by bmartinez287** [comment]
@stevendshelton, when you get a change let me know what you think.

**Comment by bmartinez287** [comment]
This PR resolves scope issue on this file. If you needed to change anything related to it. The twig file is the place to go. If you try to test it local remember to run npm run build:Drupal. Once this commits get merge you won't need to do that anymore, at least not for this twig file.

**Review by stevendshelton — APPROVED** [review]
Thanks.

**Pull request merged**
