### PR TITLE
Feature/UTC-1490-unified directory

### PR DESCRIPTION
**Pull request by brittrich**
This PR adds styles for the main unified directory landing page. The profile pages are still in development.

profile-sample

### CODE REVIEW

**Comment by bmartinez287** [comment]
Looks, great. Great work Brittaney!

**Review by bmartinez287 — APPROVED** [review]

**Review by MegShad — APPROVED** [review]

**Comment by bmartinez287** [comment]
As a side note though, I wonder if it would be better to keep the images as squares. I know its harder to crop an image at the right spot otherwise. Should the images be bigger?

**Review by stevendshelton — APPROVED** [review]
Awesome work! Thanks.

**Comment by brittrich** [comment]
> As a side note though, I wonder if it would be better to keep the images as squares. I know its harder to crop an image at the right spot otherwise. Should the images be bigger?

@bmartinez287 I can take a look at this.

**Comment by brittrich** [comment]
> > As a side note though, I wonder if it would be better to keep the images as squares. I know its harder to crop an image at the right spot otherwise. Should the images be bigger?
> 
> @bmartinez287 I can take a look at this.

Is something like this what you're thinking? I need to look a little closer at some of the margin at different browser widths, just a quick sample. 

I will say, styling like I did on the wide cards where the images span the full width/height of a side container is in the realm of possibility. I just know styling that way always felt like I was either choosing between cropping based on container auto height (which sometimes turns out poorly), or setting a fixed height for the container...pro/cons with how this looks. I can do some more exploring there if we think it's worth it to have them span a full square visually.

profile-sample-square

**Comment by bmartinez287** [comment]
Tks for looking into it @brittrich. This looks good. We might be able to do more into it but this looks like a solid version 1. Are we ready to merge this PR? It be great to have it in for some of the topics we are covering next week. Among them, a little bit about brandbar, its future, and perhaps where to place the directory and UTC people view. I can merge it in if you are good with it @stevendshelton.

**Review by stevendshelton — APPROVED** [review]

**Pull request merged**
