### PR TITLE
UTC-587: Improve menu accessibility & best prac.

### PR DESCRIPTION
**Pull request by UTCbridget**
This PR answers the following from issue #537 :

- [x] Show/hide mobile menu elements by viewport.
- [x] Looked at tab indexing: main menu, offcanvas (mobile) menu, sidebar menu, footer menu. HOWEVER: According to numerous articles, tabbing should be either set to 0 (for default DOM order) or not set at all. `tab-index="0"` is not necesary for links with hrefs.
- [x] Added aria and role attributes.
- [x] Added sr-only text to "Apply Now ribbon" and "Go to Top" buttons.
- [x] Added sr-only label to search input field.
- [x] Improved best practices:
        Ex., #block-utcsecondarymenu-offcanvas is now wrapped in `<section aria-label="mobile menu accordion"></section>`.
        Ex. 2, Top Workbench menu is now wrapped in `<section aria-label="organization root menu"></section>`.
- [x] Moved themag back-to-top-button.js to Particle.
- [x] Moved the user-action-menu.html.twig code in themag to the custom-header.html.twig in Particle.
- [x] Reconfigured bottom footer white text v. gold links issues throwing contrast errors. 

Lighthouse: Accessibility score
Screenshot 2023-04-17 at 9 58 26 AM
 = 100

Dev Axe tools: 0 Accessibility issues

Screenshot 2023-04-17 at 9 56 47 AM

Additionally, some slight margin and padding tweaks were made to the hero image and hero video blocks.

### CODE REVIEW

**Comment by bmartinez287** [comment]
Adding behaviors this way will make them part of the global bundle. Meaning it will be on the javascript file either way. That might create scenarios where it's added but it can't find and element on a page similar to the topworkbench bug.
Not sure is bad but it could lead to odd bugs.

**Comment by bmartinez287** [comment]
Some of the ARIA changes are fine even if they be hardcoded I can't see why having it would be bad. Though removing some links to the mag might make some global shared settings to stop working as they did.

**Comment by UTCbridget** [comment]
I tried adding the attributes via the superfish.menu.html.twig, but the item.XXXX were not applying my edits at all. I could add them the Drupal menu via twig, but not the superfish. I'm open to suggestions. The back-to-top was already built via a js file in themag. I just moved it to particle and added accessibility attributes. Both the superfish and the back to top buttons are global items.

**Review by UTCGilligan — COMMENTED** [review]
Looking better, good improvements.

**Pull request merged**
