### PR TITLE
Fix/UTC-168-add margin options for images

### PR DESCRIPTION
**Pull request by brittrich**
Closes Issue #168
 
This adds an option to add margin above or below a UTC Image block. Margin is added to the outer container so that caption is not impacted. Since it is a new option (not required), should not impact existing images on the site. Just adds the option for when an image is needed above cards groups or other areas where more margin is needed. Will add config.

image-margin-fix

Just let me know if there's another solution that might work better!

### CODE REVIEW

**Review by UTCbridget — APPROVED** [review]
Looks good to me! Thanks, Brittany!

**Comment by bmartinez287** [comment]
I have a few concerns in regards to the margin and padding-bottom and how that will work if the image has a caption or text that belongs to it. Not because it will alter current ones but because we might have to explain when they should use those.

**Comment by UTCbridget** [comment]
A possible solution: Conditional logic: If image has caption, true, margins don't apply? Or are different?

**Comment by brittrich** [comment]
> I have a few concerns in regards to the margin and padding-bottom and how that will work if the image has a caption or text that belongs to it. Not because it will alter current ones but because we might have to explain when they should use those.

If the image has a caption, here it is without margin (current default):

Screen Shot 2021-06-23 at 10 39 12 PM

If the user opts to add margin, it will add below the caption (on the container):

Screen Shot 2021-06-23 at 10 39 29 PM

Is this okay/expected behavior? I was imagining we wouldn't want them to adjust padding/margin directly below the image/above the caption.

**Comment by bmartinez287** [comment]
What are the values given to margin: small, medium and large?

**Review by bmartinez287 — APPROVED** [review]

**Comment by brittrich** [comment]
> What are the values given to margin: small, medium and large?

They are:

 value: mb-4
      label: Small
    -
      value: mb-8
      label: Medium
    -
      value: mb-12
      label: Large

We could change this, though. I could also do this a bit differently so the sizes aren't wired in the config (which we can't change once it's in use)...but instead are variables to be used in the twig so the sizing could be modified as needed in the future.

**Comment by bmartinez287** [comment]
That's an interesting idea. How will that look like? Will it be something we could scale?
I could see someone asking if they can have the margin option for the video block or for the table block or something else. I know at the moment some are using whitespace for it. Which is not ideal. However, if they switched to this how could we make it modular so we don't have to change a bunch of taxonomy values in production all at once but rather do the change in code and have it available everywhere for items that might need it.

Maybe a twig include that has a preset of variables? For standard margin small, medium and large. So items that are categorize and bundle together can use a taxonomy only as an if statement trigger but the value will be centralized.

If we later decided that value: 
label: Medium should be mb-2 we only had to change in one place in code and it will work. Because the level be the same for all blocks but the the value can be updated independently for all of the ones grouped together.

**Comment by brittrich** [comment]
> That's an interesting idea. How will that look like? Will it be something we could scale?
> I could see someone asking if they can have the margin option for the video block or for the table block or something else. I know at the moment some are using whitespace for it. Which is not ideal. However, if they switched to this how could we make it modular so we don't have to change a bunch of taxonomy values in production all at once but rather do the change in code and have it available everywhere for items that might need it.
> 
> Maybe a twig include that has a preset of variables? For standard margin small, medium and large. So items that are categorize and bundle together can use a taxonomy only as an if statement trigger but the value will be centralized.
> 
> If we later decided that value:
> label: Medium should be mb-2 we only had to change in one place in code and it will work. Because the level be the same for all blocks but the the value can be updated independently for all of the ones grouped together.

I think I get what you are saying, what if we have a defined "key" for what will be medium, large, etc. padding across the system. So, if we add padding options to other blocks they will have the same parameters? I was thinking the way to do this in twig specific to this block is just to have the dropdown select key / item for the block be "medium" or "small" alone. And then use those in "if" statements in twig to assign the right css class for appropriate margin based on what was selected. 

Related, another block that uses margin is the button group block. It might be worth matching them up so users know what to expect with "small" "medium" and "large."

**Comment by bmartinez287** [comment]
I agree if we could match them or define a category for them that would be great. That way making changes would not affect the end-user expectation for it.

**Comment by brittrich** [comment]
> I agree if we could match them or define a category for them that would be great. That way making changes would not affect the end-user expectation for it.

Sounds good, let me make that adjustment and then I'll update this PR.

**Comment by brittrich** [comment]
> > I agree if we could match them or define a category for them that would be great. That way making changes would not affect the end-user expectation for it.
> 
> Sounds good, let me make that adjustment and then I'll update this PR.

@bmartinez287 this is updated, do you think the way I did it will work for now? There may be a cleaner way to do those if statements...seems clunky...but I'm not sure I've handled this type scenario before without using css class modifiers. Trying to stick to tailwind.

**Comment by bmartinez287** [comment]
That's an interesting change. I think that works for now. Placing them on top makes it easier for us to extract those margins into another base twig file for custom margins later.
I think that's good for now.

**Pull request merged**
