### PR TITLE
UTC-455: Reveal autogen section menu logged-in.

### PR DESCRIPTION
**Pull request by UTCbridget**
This PR reveals the auto-generated "Main Navigation" block upon creation of a new internal page in order that the logged-in user can remove it. Code to hide duplicate "Section Menus" on the frontend is also available, but commented out in favor of a menu-block patch that should fix that.

**BEFORE:**
Desktop: The autogenerated menu is invisible whether the user logged in or not.
Screen Shot 2022-04-26 at 5 12 26 PM

AFTER:
Using CSS, the autogenerated menu is now visible and can be manually removed.
Screen Shot 2022-04-27 at 2 35 56 PM

### CODE REVIEW

**Comment by UTCGilligan** [comment]
IDK about your warning/info message. Either we want the autogenerated menu block to exist, or we don't. If we don't, then it should be removed from the twig as well. If we do want the autogenerated menu block, then the message should read "Default menu block. Configure or remove."

I believe it's a good idea for the menu block to be there when a node is created. We can let editors know they should remove redundant/empty blocks if they have added menu blocks. Either way, they are going to see the block in Layout.

**Comment by bmartinez287** [comment]
What about the ones that have multiple blocks that have been manually added?
Also, how is that working only on the ones that are empty? All blocks technically have a title.

**Comment by bmartinez287** [comment]
I wonder if it should be more narrowed a bit more to when a user is inside layout builder.

**Comment by UTCGilligan** [comment]
This seems like an imprudent use of !important, used to override .visually-hidden.

The "not last of type" in the existing CSS tells me we probably had to hide the default inserted menu block for another reason, like possibly it had a tiny bit of height by default.

**Comment by UTCbridget** [comment]
The CSS targets only the level-0 menus (no matter how many of them there are) with the .menu--main class. When a user adds a level-1+ menu, the class is is NOT .menu--main, but rather the class of the menu chosen. For example, Enrollment Management and Student Affairs menu has the class .menu--emsa. There is no .menu--main class on that nav element. The labels are siblings to the nav element. I will look at twig, but this seemed a quicker remedy. I will also change the verbiage should we keep the css solution for now.

**Comment by UTCbridget** [comment]
Message has been changed to @UTCGilligan 's suggestion. NOTE: Only the menu that has the class .menu--main displays with the aqua background and new message. Manually placed menus have a different class based on the user's menu selection, in this example Enrollment Management and Student Affairs :

Screen Shot 2022-04-27 at 3 33 44 PM

**Comment by UTCGilligan** [comment]
OK, that makes sense, as long as it only appears in Layout Builder and not in View. I also don't think we need to remove the default block from Twig. It saves a lot of time during node creation if the block is already placed. If that's the case, it's more of an enhancement than a temporary fix.

**Comment by bmartinez287** [comment]
Screen Shot 2022-04-27 at 4 10 56 PM
So menu_main only takes care of the auto generated ones but not the ones section editors might have forgotten there.

**Comment by bmartinez287** [comment]
could it be more generic than just menu main? maybe with a css attribute

**Comment by UTCbridget** [comment]
I've only seen the one page with 6 section menus on them. All the others have only had 2, the main menu and the real section menu. The ones section editors may duplicate like the https://www.utc.edu/finance-economics page (you'll have to see it in dev or test bc I already corrected it in prod) all have the same elements, attributes, classes, etc. They are identical. So if I target one, I target them all. I think this is rare, though, and is an editor error.

Screen Shot 2022-04-27 at 4 30 51 PM

**Comment by bmartinez287** [comment]
``` 

{% if content["#items"]|length < 1%}
    <p>Empty Menu Array in block </p>
  {% endif %}

```


on the block--menu-block.html.twig
I found a way to do it in twig.
Items is populated only if there are child items on that menu. Hence if the are none this should cover it.
This also works if the visibility level is greater than 1 let's say 2 or 3 and the item was chosen in at level 1.

**Comment by UTCbridget** [comment]
That removes it, but what if we want it to default to the workbench organization? That's what I was looking at. But we could table that for now and implement yours.

**Comment by bmartinez287** [comment]
That works even if we want the default one because it works with all of them we can mix both PR's actually.

**Comment by bmartinez287** [comment]
```
{#
/**
 * @file
 * Theme override for a menu block.
 *
 * Available variables:
 * - plugin_id: The ID of the block implementation.
 * - label: The configured label of the block if visible.
 * - configuration: A list of the block's configuration values.
 *   - label: The configured label for the block.
 *   - label_display: The display settings for the label.
 *   - provider: The module or other provider that provided this block plugin.
 *   - Block plugin specific settings will also be stored here.
 * - content: The content of this block.
 * - attributes: HTML attributes for the containing element.
 *   - id: A valid HTML ID and guaranteed unique.
 * - title_attributes: HTML attributes for the title element.
 * - content_attributes: HTML attributes for the content element.
 * - title_prefix: Additional output populated by modules, intended to be
 *   displayed in front of the main title tag that appears in the template.
 * - title_suffix: Additional output populated by modules, intended to be
 *   displayed after the main title tag that appears in the template.
 *
 * Headings should be used on navigation menus that consistently appear on
 * multiple pages. When this menu block's label is configured to not be
 * displayed, it is automatically made invisible using the 'visually-hidden' CSS
 * class, which still keeps it visible for screen-readers and assistive
 * technology. Headings allow screen-reader and keyboard only users to navigate
 * to or skip the links.
 * See http://juicystudio.com/article/screen-readers-display-none.php and
 * http://www.w3.org/TR/WCAG-TECHS/H42.html for more information.
 */
#}
{%
  set classes = [
    'block',
    'block-menu',
    'navigation',
    'menu--' ~ derivative_plugin_id|clean_class,
    'utc-sidebar'
  ]
%}
{% set heading_id = attributes.id ~ '-menu'|clean_id %}
  <input  class='hidden' type="checkbox" id="mobile_menu">
  <label for="mobile_menu" class="section_menu">Section Menu <i class="fas fa-bars" aria-hidden="true"></i></label>

<nav role="navigation" aria-labelledby="{{ heading_id }}"{{ attributes.addClass(classes)|without('role', 'aria-labelledby') }}>
  {# Label. If not displayed, we still provide it for screen readers. #}
  {% if not configuration.label_display %}
    {% set title_attributes = title_attributes.addClass('visually-hidden') %}
  {% endif %}
  {{ title_prefix }}
  <h2{{ title_attributes.setAttribute('id', heading_id) }}>{{ configuration.label }}</h2>
  {{ title_suffix }}
  <a href ="#bottom-sidenav" class="sr-only">Skip Sidebar</a>
  {# Menu. #}
  {% block content %}
  {% if content["#items"]|length < 1%}

    <p>Empty Menu Array in block </p>
  {% endif %}
  {{ content }}

  {% endblock %}
  <div id ="bottom-sidenav"></div>
</nav>

```

Here is the whole twig file for context

**Comment by UTCbridget** [comment]
Yea. I've been playing around with that file. Ok. I say let's go with it.

**Comment by bmartinez287** [comment]
Screen Shot 2022-04-27 at 5 25 15 PM
We might need a more generic message though.

**Comment by bmartinez287** [comment]
Blank Menu block? maybe something like that?

**Comment by bmartinez287** [comment]
In some cases it won't be autogenerated but that won't matter on such scenarios. Regardless of adding automatically or by the a section editor.

**Comment by UTCbridget** [comment]
I have discovered that even if I select a menu in the auto-generated Main Navigation, it doesn't show, the menu--main.html.twig would need to be configured, but this would be a moot point: The default menu is ALWAYS the main menu and cannot be reconfigured to be another menu by the user. The "Main Menu" is not used in this Drupal installation. For now, it would likely be best to remove it all together. I'm PRing a patch in UTCCloud to remove empty menu trees: https://www.drupal.org/files/issues/2022-03-23/menu_block_rendered_empty-3271218-2.patch.

**Comment by bmartinez287** [comment]
I tested that patch last week and unfortunately it did not work for me. I be interested to hear if it worked for you.

**Comment by bmartinez287** [comment]
I will checkout this branch to add the twig fix and merge it with some of the css work you did.

**Comment by UTCbridget** [comment]
I tested the patch as well. It did not work for me either. I removed the css file from this PR. Let me know if you need it back.

**Pull request merged**
